final specialties = [
  "psychiatry",
  "psychiatry liason",
  "renal",
  "respiratory",
  "cardiology",
  "endocrinology",
  "eye clinic",
  "gastroenterology",
  "general surgery",
  "haematology",
  "neurology",
  "neurosurgery",
  "orthopaedics",
  "rheumatology",
  "urology",
  "stroke",
  "acute oncology",
  "palliative care",
  "diabetic specialist nurse",
  "drug and alcohol team",
  "cancer referral",
  "anaemia",
  "vascular",
  "anticoagulation clinic",
  "pain team",
  "virtual ward",
  "gynaecology",
  "interventional radiology",
  "urology mdt",
  "lower gi mdt",
  "upper gi mdt",
  "endoscopy",
  "radiology - ct",
  "radiology - mri",
  "radiology - xray",
  "ultrasound",
  "echocardiogram",
  "24 hour ecg",


  //add more specialties here
];

final recentSpecialties = [
  "psychiatry",
  "psychiatry liason",
  "renal",
  "respiratory",
  "cardiology",
  "endocrinology",
  "eye clinic",
  "gastroenterology",
  "general surgery",
  "haematology",
  "neurology",
  "neurosurgery",
  "orthopaedics",
  "rheumatology",
  "urology",
  "stroke",
  "acute oncology",
  "palliative care",
  "diabetic specialist nurse",
  "drug and alcohol team",
  "cancer referral",
  "anaemia",
  "vascular",
  "anticoagulation clinic",
  "pain team",
  "virtual ward",
  "gynaecology",
  "interventional radiology",
  "urology mdt",
  "lower gi mdt",
  "upper gi mdt",
  "endoscopy",
  "radiology - ct",
  "radiology - mri",
  "radiology - xray",
  "ultrasound",
  "echocardiogram",
  "24 hour ecg",
  //Remove this hardcode and replace with actual finder
];

//List<ReferralPathway> specialties = [
  //ReferralPathway('psychiatry', 'Use the link below and download the word document. Fill it in with the relevant patient details and send to the email below/in the referral form', 'sidharthan.ilangovan1@nhs.net', 'www.google.com')
//];
